version: '3.7'
services:
    webapp:
        build:
            context: .
            dockerfile: webapp/Dockerfile
        volumes:
            - './webapp:/webapp'
            - '/webapp/node_modules'
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=development
    mongodb:
        image: mvertes/alpine-mongo
        build:
          context: .
          dockerfile: mongodb/Dockerfile
        volumes:
            - './mongodb:/data/db'
        ports:
            - '27017:27017'
        expose:
            - '27017'
    go-server:
        container_name: go-server
        build: 
            context: ./go-server
            dockerfile: ./Dockerfile
        ports:
            - '8080:8080'
        environment:
            PORT: 8080
        expose:
            - "8080"
volumes:
  mongodb:
